apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  url: https://charts.jetstack.io
  interval: {{ default "5m0s" }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: "cert-manager"
      version: "{{ .Values.certManager.version }}"
      sourceRef:
        kind: HelmRepository
        name: "jetstack"
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values: 
    installCRDs: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cf-buttahtoast
spec:
  interval: 5m
  dependsOn:
  - name: cert-manager
    namespace: "{{ .Release.Namespace }}"
  chart:
    spec:
      chart: "raw"
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: "bedag"
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    resources:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: cf-buttahtoast
      spec:
        acme:
          email: {{ .Values.certManager.cfButtahtoast.email }}
          server: https://acme-v02.api.letsencrypt.org/directory
          privateKeySecretRef:
            name: example-issuer-account-key
          solvers:
          - dns01:
              cloudflare:
                email: {{ .Values.certManager.cfButtahtoast.email }}
                apiTokenSecretRef:
                  name: cloudflare-api-token-secret
                  key: api-token
            selector:
              dnsZones:
              - "buttahtoast.ch"
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cloudflare-api-token-secret
      type: Opaque
      stringData: 
        api-token: {{ .Values.certManager.cfButtahtoast.apiToken }}