---
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lb-config
spec:
  interval: 5m
  chart:
    spec:
      chart: "raw"
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: bedag
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    templates:
    - |
      apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      metadata:
        name: intern 
      spec:
        addresses:
        - 10.123.12.90-10.123.12.100
    - |
      apiVersion: metallb.io/v1beta1
      kind: L2Advertisement
      metadata:
        name: intern
      spec:
        ipAddressPools:
        - intern
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bedag
spec:
  url: https://bedag.github.io/helm-charts/
  interval: {{ default "5m0s" }}