---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lb
spec:
  interval: 5m
  chart:
    spec:
      chart: "metallb"
      version: "{{ .Values.lb.version }}"
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgp-config
data:
  config.yaml: ""
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: metallb
spec:
  url: https://metallb.github.io/metallb
  interval: {{ default "5m0s" }}