---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring 
spec:
  interval: 5m
  chart:
    spec:
      chart: "kube-prometheus-stack"
      version: "{{ .Values.monitoring.version }}"
      sourceRef:
        kind: HelmRepository
        name: "prometheus"
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: {{ default "5m0s" }}