---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-intern
spec:
  dependsOn:
    - name: monitoring
  interval: 5m
  chart:
    spec:
      chart: "ingress-nginx"
      version: "{{ .Values.ingress.version }}"
      sourceRef:
        kind: HelmRepository
        name: "ingress"
        namespace: "{{ .Release.Namespace }}"
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    controller:
      electionID: "intern"
      ingressClass: "buttahtoast.ch/ingress-nginx-intern"
      ingressClassResource:
        name: "intern"
        controllerValue: "buttahtoast.ch/ingress-nginx-intern"
      service:
        annotations: 
          metallb.universe.tf/address-pool: "intern"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ingress
spec:
  url: https://kubernetes.github.io/ingress-nginx
  interval: {{ default "5m0s" }}